// -----------------------------------------------------------
// Copyright My copy Veso

// <auto-generated>
//		This code was generated from a T4 template.
//		Changes to this .cs file will be lost!
// </auto-generate>
// -----------------------------------------------------------

namespace T4Template
{
	using System;
	[assembly: log4net.Config.XmlConfigurator(ConfigFile = "Web.config", Watch = true)]

    class Program
    {
        static void Main()
        {
			// This content was generated from a template 
			// on 8/21/2015 12:52:07 AM
			string name = "Joro";
			Console.WriteLine(name);
        }
    }
}
